# Generated by Django 3.0.7 on 2020-06-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='senha',
        ),
    ]
