# Generated by Django 3.0.7 on 2020-06-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0002_remove_aula_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
