# Generated by Django 3.0.7 on 2020-06-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0004_aulaaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=560)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aula.Aula')),
            ],
        ),
    ]
