# Generated by Django 3.0.7 on 2020-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aula', '0005_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
